name: Build and Deploy Calculator App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Images (Frontend & Backend)
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/calculator-frontend:latest ./calculator
        docker build -t ${{ secrets.DOCKER_USERNAME }}/calculator-backend:latest ./backend

    - name: Push Docker Images to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/calculator-frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/calculator-backend:latest

    - name: Run Containers with Docker Compose
      run: |
        docker-compose up -d
